### PR TITLE
Updated gem for Rails 4 compatibility

### PR DESCRIPTION
**Pull request by emaiax**
Hello @bcm.

I updated jquery-raty to the latest version and make the gem compatible with Rails 4.

Thanks.

### CODE REVIEW

**Comment by kevin-jj** [comment]
@bmc  Could you merge this, please?

**Comment by bmc** [comment]
Merged. I need to put a new release in place at some point.

**Comment by kevin-jj** [comment]
@bmc  When to release new version?

**Comment by bmc** [comment]
I’m traveling right now (in Asia, on business). I’ll try to get to it when I return, later this week.

**Comment by kevin-jj** [comment]
@bmc  Thanks. Enjoy your trip

**Pull request merged**
